### ISSUE TITLE
Events color on Gnome 3.38.1

### ISSUE THREAD

**Issue by felipeehm** [rose-pine/gtk#1]
Hi, i had a problem with the gnome shell notification area, the events area shows with default color. This on Gnome 3.38.1.
I managed to solve it just copying the code from other theme and changing the color.

![Captura de pantalla de 2020-11-22 02-36-28](https://user-images.githubusercontent.com/34879656/99896446-64427100-2c6f-11eb-8e8e-65a7b9b56f73.png)

**Comment by ThatOneCalculator** [comment]
Awesome! Thanks for testing it in 3.38. If you could make a pull request, I'd be happy to merge it!
