### ISSUE TITLE
Add libadwaita theme and fix legacy theming

### ISSUE THREAD

**Issue by ashbork** [rose-pine/gtk#10]
Following the release of libadwaita and its adoption in GNOME 42 this theme no longer works as expected on updated GNOME instances. 

### GTK 4
Theming within GTK 4 seems to be easier than ever with a single css file allowing for pretty extensive modifiactions of pretty much every part of the toolkit. A new set of themes could be released (I'm already working on one, though I'm not sure whether to base it on this repository or create a new one for gtk4).

### Regarding the legacy theme
As of now, the gtk-3 theme can still be used with GNOME Tweaks (as shown below).
![image](https://user-images.githubusercontent.com/82605611/164996700-5cfe8d2e-f178-4e15-b7fd-38b363eba079.png)
However, if you're using GNOME in dark mode (which you probably are if you're using a dark them. e such as RP or RPM) the background colors are flipped. Example:
![image](https://user-images.githubusercontent.com/82605611/164996780-9dbf325f-9bc3-44fc-aef8-8ce3d82aeda3.png)
The workarounds for this issue could be either of these:

- refactoring the legacy (gtk-3) theme by changing the background color so that it gets flipped to the correct one
- creating the new GTK 4 theme as a light theme

Both of these aren't ideal and will be annoying for users to install and understand, but the latter seems doable.

**Comment by mvllow** [comment]
I think ideally we would have a gtk3 folder and gtk4 within this repo (or only gtk3 and have the root be the latest version?). If you want to tackle this that would be lovely and much appreciated 😌

**Comment by ashbork** [comment]
I'll certainly see what I can do!

**Comment by ThatOneCalculator** [comment]
Sadly I have literally no clue how gtk4 themes are made lol
