### ISSUE TITLE
Updating to the new GNOME 42.0 LTS broke all theming

### ISSUE THREAD

**Issue by diorcula** [rose-pine/gtk#11]
Os: Pop!_OS 22.04 LTS
GNOME: 42.0
Windowing system: X11
-----------

Just updated to the new Pop version, and when rebooted all themeing is off and looks broken.
Tried for all themes in GTK.

Will try reinstalling the GTK theme to see if that helps

**Comment by ThatOneCalculator** [comment]
Known problem with GTK4.

**Comment by ThatOneCalculator** [comment]
Also since it's all GTK3 themes, I'm going to close this issue. Please make sure to research the differences of GTK3 and GTK4.
