### ISSUE TITLE
Add new release 

### ISSUE THREAD

**Issue by ashbork** [rose-pine/gtk#14]
Hi,
I've been working on an updated readme.md to account for GTK4. I think it'd be easier to install the theme if a release was made, containing zipped parts of the theme. One suggestion: splitting the icons instead of packing them into one file may be a good idea - if an user knows which theme they want they won't be downloading 3x the icons.

**Comment by mvllow** [comment]
Done 😌 Let me know if anything needs changed with the release format

Edit: I'm happy to break out the icons, but would need some guidance or a PR – not too familiar with GTK in general

**Comment by ashbork** [comment]
That's perfect, it'd be great to also include the three directories under /icons (/icons/rose-pine-<variant>-icons) as three separate archives - they're a huge bunch of files and it'd be a pain to have to download them at once. The current structure is great - we just need the icons ^^

**Comment by mvllow** [comment]
Updated with icons

**Comment by ashbork** [comment]
That's grand, thank you!
