### ISSUE TITLE
Show some images in the main readme gallery

### ISSUE THREAD

**Issue by mvllow** [rose-pine/gtk#17]
Breaking out the plethora of images into the gallery is lovely. I do think the main readme could benefit from having an image per variant – maybe a collage like recommended in #15.

**Example**

<img width="1920" alt="blur 7" src="https://user-images.githubusercontent.com/1474821/166740504-9768c3b0-3875-48be-9d53-09804fd2cb1f.png">

**Comment by ashbork** [comment]
I could make something of this sort, maybe including GTK3 apps too? A legacy file manager and GTK4 settings to show both parts of the theme is my idea. Some DEs still rely solely on GTK3 as far as I know and even those that don't will need it for a coherent experience.

**Comment by mvllow** [comment]
That would be super helpful. Thank you for all your work on this 😌

**Comment by ashbork** [comment]
Sorry for the delay - I'll try spinning something up now
