### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kirasok** [rose-pine/gtk#25]
Hi! I want to make an [AUR](https://aur.archlinux.org/) package for this theme. However, I can't publish [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD) without license. Could license be added to this project?

**Comment by ThatOneCalculator** [comment]
If themes aren't licensed in-repo, they inherent the license of the base theme repo, that being the MIT license.

**Comment by kirasok** [comment]
Thanks! I've published package as [rose-pine-gtk-theme](https://aur.archlinux.org/packages/rose-pine-gtk-theme)

**Comment by ThatOneCalculator** [comment]
Mentioned the AUR package in the README, thank you :)
