### ISSUE TITLE
Invisible header bars

### ISSUE THREAD

**Issue by Hungamer24** [rose-pine/gtk#33]
I installed the rose pine dawn theme, and it works well with native gnome apps, but for some reason apps like hexchat, discord, scilab etc. have transparent headerbars and with lighter wallpapers the icons and text are unreadable.  I can't for the life of me figure out what might be the issue. For some reason the header bars work when in dark mode.

i think i might have screwed up something in the installation as i haven't found other people online who had the same issue, but idk

thx for the help in advance.

**Comment by ThatOneCalculator** [comment]
This seems to be an issue specific to your setup.
