### ISSUE TITLE
GNOME nautilus sidebar not applying theme

### ISSUE THREAD

**Issue by fqidz** [rose-pine/gtk#34]
![image](https://github.com/rose-pine/gtk/assets/82884264/cdadd18e-da33-45a9-a2c0-f9bb1f9769de)

using Fedora 39
using gnome shell 45.4
using adw-gtk3 v5.2
applied the theme using gradience

Idk whats wrong but the sidebar for the nautilus file manager is not applying the theme. It seems like it's just using the default theme.

**Comment by ThatOneCalculator** [comment]
Please report on the gradience community themes repo, not here

**Comment by zDyant** [comment]
> Please report on the gradience community themes repo, not here

Should I report on this bug on Nixos Pkgs?
![image](https://github.com/rose-pine/gtk/assets/102763838/325261be-7ae3-4b18-b0f9-871949795388)

**Comment by ThatOneCalculator** [comment]
I don't know why this would be related to NixOS.

**Comment by zDyant** [comment]
> I don't know why this would be related to NixOS.

Was installed using nixpkgs, maybe it's using an outdated version of the theme?

Besides, the error persists

**Comment by ThatOneCalculator** [comment]
We do not provide support for unofficial packages.
