### ISSUE TITLE
Sidebar theming

### ISSUE THREAD

**Issue by Jeffser** [rose-pine/gtk#36]
Hi, thanks for the great theme.

There are some Adwaita apps that use sidebars that aren't themed right now

![image](https://github.com/user-attachments/assets/5f782955-d636-4aff-9e00-7a39a28d12ae)

After some digging I found out which variables correspond to the sidebar:

```
@define-color sidebar_backdrop_color #26233A;
@define-color sidebar_bg_color #26233A;
```

Once they are applied the app looks like this

![image](https://github.com/user-attachments/assets/a8a51388-0e1a-4f9a-85c7-051efcc3b183)

I think these variables should be included by default, maybe with a different color tho. Thanks

**Comment by LordImmaculate** [comment]
Fixed it: #37
