### ISSUE TITLE
Use main branch

### ISSUE THREAD

**Issue by mvllow** [rose-pine/gtk#4]
Shouldn't disrupt anything but wanted to leave the honors to you since this is your baby @ThatOneCalculator ☺️

I created the main branch, just need to make it default and delete master

**Comment by ThatOneCalculator** [comment]
Since I don't actually have ownership on this repo (when I transferred it to the org, I forgot to add the team), so I can't change the default branch

**Comment by mvllow** [comment]
You should be an admin now 😌

**Comment by ThatOneCalculator** [comment]
Okie dokie
