### ISSUE TITLE
Dawn & Moon variants

### ISSUE THREAD

**Issue by Jimmysit0** [rose-pine/gtk#5]

**Comment by ThatOneCalculator** [comment]
Soon™

**Comment by dkirchhof** [comment]
Hey, is it still planned? What has happend with the [PR](https://github.com/rose-pine/gtk/pull/6)? Why did you close it?  
It would be so nice to have the bright theme :)

**Comment by ThatOneCalculator** [comment]
OP closed it after I asked a question. No clue why.
![Screenshot from 2021-09-30 13-25-31](https://user-images.githubusercontent.com/44733677/135525470-32583245-51af-41a7-a98c-523b8aa13a25.png)

**Comment by Jimmysit0** [comment]
This wasn't added to the repo or anything - Why was it closed? @ThatOneCalculator

**Comment by ThatOneCalculator** [comment]
Mostly cuz there was no response from the OP of the pr + new gtk ones being released very soon

**Comment by mvllow** [comment]
Should leave it open until the themes are added, but looks like they are now. Appreciate the hard work on this one @ThatOneCalculator
