### ISSUE TITLE
Add shell theme

### ISSUE THREAD

**Issue by tanaybhomia** [rose-pine/gtk#8]
I have downloaded the theme in Gnome and applied it tho it does not have a gnome shell theme which just makes it looks bad. and I thought I might use Dracula but those 2 does not go well

**Comment by mvllow** [comment]
here is our gnome terminal theme

https://github.com/rose-pine/gnome-terminal

**Comment by ThatOneCalculator** [comment]
>

**Comment by ThatOneCalculator** [comment]
Hey @mvllow! In GNOME, the shell theme does *not* mean the terminal, instead, it's the surrounding UI specifically for GNOME. @Deottive, the GTK theme does not have a GNOME shell counterpart as of right now, but it's something I'd be happy to add in the future! :)

**Comment by tanaybhomia** [comment]
Thank you, because without the shell theme the GTK theme falls apart and when I tried to use this theme with Dracula it just looks weired [my mistake for thinking that it will] but still I would be happy to use this in my setup if you provide the shell theme

**Comment by ThatOneCalculator** [comment]
Yea. I don't use GNOME anymore, so I'll have to do some research on *how* to actually make a shell theme lmao

**Comment by ghost** [comment]
+1 this

was trying to setup this theme and was kinda sad that gnome tweaks didn't have the shell theme :(

**Comment by tanaybhomia** [comment]
Still no improvement ? Can you give me a resource for trying to create a shell theme using another shell theme

**Comment by ThatOneCalculator** [comment]
Honestly I wouldn't know. That research is pretty much up to you at this point.

**Comment by tanaybhomia** [comment]
Is it even under the process or even considerd ?

**Comment by mvllow** [comment]
> Still no improvement ? Can you give me a resource for trying to create a shell theme using another shell theme 

Please use stackoverflow for questions. Eg. https://askubuntu.com/questions/68976/how-can-i-create-themes-for-gnome-shell

**Comment by tanaybhomia** [comment]
I have searched this same question but I dont think it really had anything
to help me with this in the issue.

**Comment by diorcula** [comment]
as of now i use a bigsur like shell, which does not look all too out of place, so i might edit that theme to be compliant with the Pine colours.

**Comment by tanaybhomia** [comment]
Yes Thank you just be sure to reduce the corner size to something like 8

**Comment by diorcula** [comment]
this point didn't make my todo list for a while, but in all honesty i can only probably start trying this this summer as i'm out of time and have no clue how or edit/make shell themes

**Comment by ashbork** [comment]
Hey, check [this](https://www.gnome-look.org/p/1810542) out! Someone did it on their own, hah. May be a good idea to contact them and ask if they want to be a contributor!

**Comment by ashbork** [comment]
I asked them if it's okay if we integrate the shell theme into our repo ([issue here](https://github.com/Fausto-Korpsvart/Rose-Pine-GTK-Theme/issues/2)). I made some changes to make it a bit more flat but it's pretty much perfect - simple, easy on the eyes and in accordance to the palette.

**Comment by diorcula** [comment]
@maybork awesome! excited to see it coming :)

**Comment by ashbork** [comment]
Right now the shell theme is up at the repo I mentioned, I can release a fork (I made some tweaks which work with the basic style of RP, of course in my opinion) if anyone's interested.
